"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([[170],{

/***/ 5507:
/***/ (function(__unused_webpack_module, __webpack_exports__, __webpack_require__) {

/* harmony import */ var _Code_Common_Tools_Tools__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(6543);

let identity = _Code_Common_Tools_Tools__WEBPACK_IMPORTED_MODULE_0__/* .StrRandom */ .dJ(8);
const Logger = {
  Format: function () {
    let level = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 'info';
    let message = arguments.length > 1 ? arguments[1] : undefined;
    return `[${level}][${identity}][${_Code_Common_Tools_Tools__WEBPACK_IMPORTED_MODULE_0__/* .StrDate */ .Ih(new Date(), "hh:mm:ss.S")}]${message}`;
  },
  SetId: function () {
    let id = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : null;
    let backup = identity;
    if (id == null) {
      identity = _Code_Common_Tools_Tools__WEBPACK_IMPORTED_MODULE_0__/* .StrRandom */ .dJ(8);
      return backup;
    }
    identity = id;
    return backup;
  },
  GetId: function () {
    return identity;
  },
  Header: function () {
    return `[${identity}][${_Code_Common_Tools_Tools__WEBPACK_IMPORTED_MODULE_0__/* .StrDate */ .Ih(new Date(), "hh:mm:ss.S")}]`;
  }
};
/* harmony default export */ __webpack_exports__.A = (Logger);

/***/ }),

/***/ 6221:
/***/ (function(__unused_webpack_module, __webpack_exports__) {

/*
* 本文件内容不要人为修改，本文件由"python3 Christmas.py Input/MergeCode/LinkModule"生成
* 如果再次运行生成脚本，人为修改的代码将被删除
* 本文件模板请修改Christmas/Template/LinkModule/ErrorCode.templ
* 模块ErrorCode请修改Code/Module/??/Once.Link
* 修改结束后，终端执行"python3 Christmas.py Input/MergeCode/LinkModule"重新生成此文件
*
* The contents of this file should not be modified. This file is generated by "python3 Christmas.py Input/MergeCode/LinkModule"
* If the generation script is run again, the artificially modified code will be deleted
* This file template settings, please modify Christmas/Template/LinkModule/ErrorCode.templ
* Module ErrorCode settings, please modify Code/Module/??/Once.Link
* After the modification, execute "python3 Christmas.py Input/MergeCode/LinkModule" in the terminal to regenerate this file.
*/
const ErrorCode = Object.freeze({
  //TIPS::ErrorCode enum
  ERR_OK: ["200", "OK"],
  ERR_Module__DataFilling_Exception: ["E-FP(_DataFilling)", "_DataFilling exception"],
  ERR_Module__DataFilling_SessionStorage_Null: ["E-FP(_DataFilling)", "_DataFilling Session storage get null"],
  ERR_Module__DataFilling_LocalStorage_Null: ["E-FP(_DataFilling)", "_DataFilling Local storage get null"],
  ERR_Module__DataFilling_Switch_Null: ["E-FP(_DataFilling)", "_DataFilling Switch data get null"],
  ERR_Module_ExtendJS_Exception: ["E-FP(ExtendJS)", "ExtendJS exception"],
  ERR_Module_ExtendJS_Action_Lack: ["E-FP(ExtendJS)", "ExtendJS action lack"],
  ERR_Module__OperRoute_Exception: ["E-FP(_OperRoute)", "_OperRoute exception"],
  ERR_Module__OperRoute_Action_Lack: ["E-FP(_OperRoute)", "_OperRoute action lack"],
  ERR_Module__OperRoute_RouteListen_Illegal: ["E-FP(_OperRoute)", "_OperRoute RouteListen call illegal"],
  ERR_Module__BrokerUI_Exception: ["E-FP(_BrokerUI)", "_BrokerUI exception"],
  ERR_Module__BrokerUI_NoListen: ["E-FP(_BrokerUI)", "_BrokerUI There is not listen"],
  //TIPS::ErrorCode functions
  IsError: function (code) {
    let skip = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : [];
    if (code === ErrorCode.ERR_OK) {
      return false;
    }
    if (skip.length !== 0 && code in skip) {
      return false;
    }
    return true;
  },
  IsErrorCode: function (code) {
    if (!Array.isArray(code) || code.length !== 2) {
      return false;
    }
    return Object.values(ErrorCode).some(value => value === code);
  },
  GetCode: function (code) {
    if (code instanceof Array && code.length > 0) {
      return code[0];
    }
    return "unknown";
  },
  GetMessage: function (code) {
    if (code instanceof Array && code.length > 1) {
      return code[1];
    }
    return "unknown";
  }
});
/* harmony default export */ __webpack_exports__.A = (ErrorCode);

/***/ }),

/***/ 6543:
/***/ (function(__unused_webpack_module, __webpack_exports__, __webpack_require__) {


// EXPORTS
__webpack_require__.d(__webpack_exports__, {
  U_: function() { return /* reexport */ CallBack; },
  M8: function() { return /* reexport */ CompActCall; },
  _R: function() { return /* reexport */ CompActEvent; },
  Yw: function() { return /* reexport */ CompActGet; },
  IC: function() { return /* reexport */ CompActSet; },
  _q: function() { return /* reexport */ CompConfigSet; },
  zP: function() { return /* reexport */ CompContext; },
  eA: function() { return /* reexport */ CompTemplGet; },
  I7: function() { return /* reexport */ JsonPathSet; },
  xG: function() { return /* reexport */ _JsonPath_JsonPathValue; },
  HU: function() { return /* reexport */ Merge; },
  di: function() { return /* reexport */ MergeDefault; },
  tV: function() { return /* reexport */ ObjectClone; },
  A2: function() { return /* reexport */ ParamRead; },
  w1: function() { return /* reexport */ PubSubCancel; },
  XB: function() { return /* reexport */ PubSubListen; },
  Id: function() { return /* reexport */ PubSubSend; },
  Ih: function() { return /* reexport */ StrDate; },
  dJ: function() { return /* reexport */ StrRandom; },
  Af: function() { return /* reexport */ TemplAdd; },
  Sy: function() { return /* reexport */ TemplMark; }
});

// UNUSED EXPORTS: CompChildCall, ObjectClean, ObjectCopy, ParamGet, ParamGetStr, PubSubCheck, TemplGet

;// ./Code/Common/Tools/_Str.js
//TIPS::Change date object to the format string
//>>date::Date object, e.g., new Date()
//>>format::The format of the output string, e.g., "yyyy-MM-dd hh:mm:ss.S"
//>>return::The format string
//>>return::""
function StrDate(date) {
  let format = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : "yyyy-MM-dd hh:mm:ss";
  try {
    const year = date.getFullYear();
    const month = date.getMonth() + 1;
    const day = date.getDate();
    const hours = date.getHours();
    const minutes = date.getMinutes();
    const seconds = date.getSeconds();
    const milliseconds = String(date.getMilliseconds()).padStart(3, '0');
    return format.replace('yyyy', year).replace('yy', String(year).slice(2)).replace('MM', String(month).padStart(2, '0')).replace('M', month).replace('dd', String(day).padStart(2, '0')).replace('d', day).replace('hh', String(hours).padStart(2, '0')).replace('h', hours).replace('mm', String(minutes).padStart(2, '0')).replace('m', minutes).replace('ss', String(seconds).padStart(2, '0')).replace('s', seconds).replace('S', milliseconds);
  } catch (e) {
    console.debug("Common-Tools StrDate exception", e);
  }
  return "";
}

//TIPS::Get random string
//>>length::Length of the output string
//>>return::The random string
//>>return::""
function StrRandom() {
  let length = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 8;
  try {
    let lengthNum = Number(length);
    lengthNum = isNaN(lengthNum) ? 8 : lengthNum;
    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    let randomString = '';
    randomString += characters.charAt(Math.floor(Math.random() * 26));
    randomString += characters.charAt(Math.floor(Math.random() * 26) + 26);
    randomString += characters.charAt(Math.floor(Math.random() * 10) + 52);
    for (let i = 3; i < lengthNum; i++) {
      randomString += characters.charAt(Math.floor(Math.random() * characters.length));
    }
    return randomString.split('').sort(() => Math.random() - 0.5).join('');
  } catch (e) {
    console.debug("Common-Tools StrDate exception", e);
  }
  return "";
}

// EXTERNAL MODULE: ./node_modules/lodash-es/cloneDeep.js + 17 modules
var cloneDeep = __webpack_require__(8592);
// EXTERNAL MODULE: ./node_modules/pubsub-js/src/pubsub.js
var pubsub = __webpack_require__(3224);
var pubsub_default = /*#__PURE__*/__webpack_require__.n(pubsub);
// EXTERNAL MODULE: ./node_modules/lodash-es/isString.js
var isString = __webpack_require__(9703);
;// ./Code/Common/Tools/_Object.js
//TIPS::Clean the object
//>>value::The object will be clean
function ObjectClean(value) {
  try {
    if (Array.isArray(value)) {
      value.splice(0, value.length);
      return;
    }
    if (value instanceof Object) {
      for (const key in value) {
        delete value[key];
      }
    }
  } catch (e) {
    console.debug("Common-Tools ObjectClean exception", e);
  }
}

//TIPS::Add the source object to the target object
//>>target::Target object([],{})
//>>source::Source object([],{})
//         - If target and source are both array([]), add elements to target
//         - If target and source are both object({}), add elements to target
//         - Else return false
//>>isDeepClone::Whether to expand the object, deep copy
//>>return::true/false
function ObjectCopy(target, source) {
  let isDeepClone = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : false;
  try {
    if (!(target instanceof Object && source instanceof Object)) {
      return false;
    }
    if (Array.isArray(target) && Array.isArray(source)) {
      const sourceClone = isDeepClone ? ObjectClone(source) : source;
      target.push(...sourceClone);
      return true;
    }
    if (!Array.isArray(target) && target instanceof Object && !Array.isArray(source) && source instanceof Object) {
      const sourceClone = isDeepClone ? ObjectClone(source) : source;
      for (const key in sourceClone) {
        target[key] = sourceClone[key];
      }
      return true;
    }
  } catch (e) {
    console.debug("Common-Tools ObjectCopy exception", e);
  }
  return false;
}

//TIPS::Clone the source object(deep copy)
//>>value::Source object([],{})
//>>return::new object
function ObjectClone(value) {
  const newObj = Array.isArray(value) ? [] : {};
  try {
    if (value === null || typeof value !== 'object') {
      return value;
    }
    if (Array.isArray(value)) {
      return value.map(item => ObjectClone(item));
    }
    for (const key in value) {
      if (value.hasOwnProperty(key)) {
        newObj[key] = ObjectClone(value[key]);
      }
    }
  } catch (e) {
    console.debug("Common-Tools ObjectCopy exception", e);
  }
  return newObj;
}

// EXTERNAL MODULE: ./node_modules/lodash-es/isObject.js
var isObject = __webpack_require__(3149);
;// ./Code/Common/Tools/_JsonPath.js

function JsonPathSet_Set(data, keys, value) {
  if (keys.length === 1) {
    if (value === undefined) delete data[keys[0]];else data[keys[0]] = value;
    return true;
  } else if (keys.length > 1) {
    let key = keys.shift();
    const index = /^(0|[1-9][0-9]*)$/.test(key) ? Number(key) : -1;
    if (Array.isArray(data) && index < data.length) key = index;else if (Array.isArray(data) && index >= data.length) data[index] = {};else if (!Array.isArray(data) && !data.hasOwnProperty(key)) data[key] = {};
    if (typeof data[key] !== 'object') data[key] = {};
    return JsonPathSet_Set(data[key], keys, value);
  }
  return false;
}
function JsonPathValue_Get(data, keys, listIndex) {
  if (keys.length === 0) return data;
  const key = keys.shift();
  if (Array.isArray(data) && /^(0|[1-9][0-9]*)$/.test(key)) {
    const index = parseInt(key);
    if (index >= 0 && index <= data.length) {
      listIndex.push(index);
      return JsonPathValue_Get(data[key], keys, listIndex);
    }
  } else if (data && (0,isObject/* default */.A)(data) && data.hasOwnProperty(key)) return JsonPathValue_Get(data[key], keys, listIndex);
  return undefined;
}

//TIPS::Get the value by the json path
//>>key::Json path(use '>>' to locate), such as 'get##key_1>>2>>key_3'
//>>data::Source object
//>>listIndex::Mark the array index list
//>>return::Get value
//>>return::undefined
function _JsonPath_JsonPathValue(key, data) {
  let listIndex = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : [];
  try {
    return JsonPathValue_Get(data, key.split(">>"), listIndex);
  } catch (e) {
    console.debug("Common-Tools JsonPathValue exception", e);
    return undefined;
  }
}

//TIPS::Set the value by the json path
//>>key::Json path(use '>>' to locate), such as 'get##key_1>>2>>key_3'
//>>target::Target object
//>>data::Inserted value, 'undefined' means delete key
//>>return::true/false
function JsonPathSet(key, target) {
  let data = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : undefined;
  try {
    return JsonPathSet_Set(target, key.split(">>"), data);
  } catch (e) {
    console.debug("Common-Tools JsonPathSet exception", e);
    return false;
  }
}

;// ./Code/Common/Tools/_Param.js


//TIPS::Get param according the key
//>>key::The key of the param
//>>defaultValue::The default value. It can be 'null', it is equivalent to not limiting the type
//>>moduleParam::Get the value corresponding to the 'key' in this object
//              - If the acquisition fails, the 'defaultValue' is returned;
//              - If the string starting with 'get##' is obtained, it will continue to search for value in 'passParam' as a 'new key';
//              - If the same value as the 'defaultValue' type is obtained, it will be used as the return value;
//>>passParam::Get the value corresponding to the 'new key'(get from moduleParam) in this object
//            - The 'new key' can be set as json path(use '>>' to locate), such as 'get##key_1>>2>>key_3';
//            - If the acquisition fails, the 'defaultValue' is returned;
//            - If the same value as the 'defaultValue' type is obtained, it will be used as the return value;
//>>return::Value
function ParamRead(key, defaultValue, moduleParam) {
  let passParam = arguments.length > 3 && arguments[3] !== undefined ? arguments[3] : null;
  try {
    //WHEN::Get from passParam
    const realKey = moduleParam[key];
    if (passParam !== null && typeof realKey === "string" && realKey.startsWith("get##")) {
      //STEP-IN::Get value
      let returnValue = _JsonPath_JsonPathValue(realKey.substring("get##".length), passParam);
      if (returnValue !== undefined && defaultValue === null) {
        return returnValue;
      } else if (typeof returnValue === typeof defaultValue) {
        return returnValue;
      }

      //WHEN-IN::Value is string(It may be need to trans type)
      if (typeof returnValue === "string") {
        if (typeof defaultValue === 'number') {
          returnValue = Number(returnValue);
          if (!isNaN(returnValue)) {
            return returnValue;
          }
        } else if (typeof defaultValue === 'boolean') {
          returnValue = returnValue.toLowerCase() === "true";
          return returnValue;
        } else if (typeof defaultValue === 'object') {
          try {
            returnValue = JSON.parse(returnValue);
            return returnValue;
          } catch (e) {
            return defaultValue;
          }
        }
      }
      return defaultValue;
    }

    //WHEN::Get from moduleParam
    if (moduleParam.hasOwnProperty(key)) {
      if (defaultValue === null) {
        return moduleParam[key];
      } else if (typeof moduleParam[key] === typeof defaultValue) {
        return moduleParam[key];
      }
    }
  } catch (e) {
    console.debug("Common-Tools ParamRead exception", e);
  }
  return defaultValue;
}

//TIPS::Get param according the key
//>>key::The key of the param.The 'key' can be set as json path(starting with 'get##' and use '>>' to locate), such as 'get##key_1>>2>>key_3'
//>>defaultValue::The default value. It can be 'null', it is equivalent to not limiting the type
//>>moduleParam::Get the value corresponding to the 'key' in this object
//              - If the acquisition fails, the 'defaultValue' is returned;
//              - If the same value as the 'defaultValue' type is obtained, it will be used as the return value;
//>>return::Value
function ParamGet(key, defaultValue, param) {
  try {
    //STEP::Get from param
    if (param.hasOwnProperty(key)) {
      if (defaultValue === null) {
        return param[key];
      } else if (typeof param[key] === typeof defaultValue) {
        return param[key];
      }
    }

    //STEP::Try Json path
    if (typeof key === "string" && key.startsWith("get##")) {
      let returnValue = _JsonPath_JsonPathValue(key.substring("get##".length), param);
      if (returnValue !== undefined && defaultValue === null) {
        return returnValue;
      } else if (typeof returnValue === typeof defaultValue) {
        return returnValue;
      }
    }
  } catch (e) {
    console.debug("Common-Tools ParamGet exception", e);
  }
  return defaultValue;
}

//TIPS::Get param according the key, and It will be forcibly converted to string type
//>>key::The key of the param.The 'key' can be set as json path(starting with 'get##' and use '>>' to locate), such as 'get##key_1>>2>>key_3'
//>>defaultValue::The default value（must be string tpye）.
//>>param::Get the value corresponding to the 'key' in this object
//              - If the acquisition fails, the 'defaultValue' is returned;
//>>return::Value
function ParamGetStr(key, defaultValue, param) {
  try {
    //STEP::Get from param
    if (param.hasOwnProperty(key)) {
      return typeof param[key] === 'object' ? JSON.stringify(param[key]) : `${param[key]}`;
    }

    //STEP::Try Json path
    if (typeof key === "string" && key.startsWith("get##")) {
      let returnValue = JsonPathValue(key.substring("get##".length), param);
      if (returnValue !== undefined) {
        return typeof param[key] === 'object' ? JSON.stringify(returnValue) : `${returnValue}`;
      }
    }
  } catch (e) {
    console.debug("Common-Tools ParamGet exception", e);
  }
  return defaultValue;
}

;// ./Code/Common/Tools/_CallBack.js




function CallBack_Style(setting) {
  //STEP::Get query/style setting
  setting = setting.substring('style##'.length);
  const [query, styleSet] = setting.split(/>>/, 2);

  //STEP::Get element
  const element = document.querySelector(query);
  if (element === null) return;

  //STEP::Set style
  const styles = styleSet.split(';');
  styles.forEach(style => {
    if (style.trim()) {
      const [property, value] = style.split(':');
      const prop = property.trim();
      let val = value.trim();
      let important = false;
      if (val.endsWith('!important')) {
        important = true;
        val = val.replace('!important', '').trim();
      }
      if (important) element.style.setProperty(prop.trim(), val.trim(), 'important');else element.style.setProperty(prop.trim(), val.trim());
    }
  });
}
function CallBack_Css(setting) {
  //STEP::Get query/style setting
  let mode = "";
  if (setting.startsWith("css##")) {
    setting = setting.substring('css##'.length);
    mode = "toggle";
  } else if (setting.startsWith("css add##")) {
    setting = setting.substring('css add##'.length);
    mode = "add";
  } else if (setting.startsWith("css remove##")) {
    setting = setting.substring('css remove##'.length);
    mode = "remove";
  }

  //STEP::Get element
  const [query, cssSet] = setting.split(/>>/, 2);
  const element = document.querySelector(query);
  if (element === null) return;

  //STEP::Set class
  const classes = cssSet.split(' ');
  switch (mode) {
    case "toggle":
      const allExist = classes.every(cls => element.classList.contains(cls));
      if (allExist) element.classList.remove(...classes);else element.classList.add(...classes);
      break;
    case "add":
      element.classList.add(...classes);
      break;
    case "remove":
      element.classList.remove(...classes);
      break;
  }
}

//TIPS::Call back
//>>call::Target callback address
//       - Array type([]), means calling list
//       - String type("") and Starting with 'pack##', calling parent 'pack component'. The data passed is the data recorded in 'parentContext'. After 'pack##', you can set '_action', which will automatically supplement the '_action' set in the data, such as 'pack##onClick'
//       - String type(""), calling the PubSub channel, the data passed is the data recorded in 'data'(param)
//       - Function type, calling the Function, the data passed is the data recorded in 'data'(param)
//       - Object type({}), detailed settings, the format is {"_call":"","_data":{}}, '_call' equivalent to 'call', "_data" equivalent to 'data'
//>>data::Call value
//>>return::true/false
function CallBack(call) {
  let data = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
  let event = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : null;
  let parentContext = arguments.length > 3 && arguments[3] !== undefined ? arguments[3] : null;
  let isSync = arguments.length > 4 && arguments[4] !== undefined ? arguments[4] : false;
  let isFailMark = arguments.length > 5 && arguments[5] !== undefined ? arguments[5] : false;
  let isPackCallUseData = arguments.length > 6 && arguments[6] !== undefined ? arguments[6] : false;
  try {
    //STEP::Check target
    if (call === null || call === "") return;

    //WHEN::Array call list
    if (Array.isArray(call)) {
      for (const item of call) CallBack(item, data, event, parentContext, isSync, isFailMark, isPackCallUseData);
      return;
    }
    if (data === null) data = {};

    //STEP::Call back
    //WHEN::Parent pack component call(pack##)
    if (typeof call === "string" && call.startsWith("pack##")) {
      if (parentContext === null) return;
      const parentData = isPackCallUseData ? data : ParamGet("_data", {}, parentContext);
      const targetCall = ParamGet("_call", () => {}, parentContext);
      const actionKey = call.substring('pack##'.length);
      const callData = ObjectClone(parentData);
      callData["_action"] = actionKey;
      targetCall(callData, event);
      return;
    }
    if (typeof call === "string" && (call.startsWith("css##") || call.startsWith("css add##") || call.startsWith("css remove##"))) {
      CallBack_Css(call);
      return;
    }
    if (typeof call === "string" && call.startsWith("style##")) {
      CallBack_Style(call);
      return;
    }
    //WHEN::PubSub id call
    if (typeof call === "string") return PubSubSend(call, ObjectClone(data), isSync, isFailMark);
    //WHEN::Function
    if (call instanceof Function) {
      if (isSync) return call(ObjectClone(data));else setTimeout(() => {
        call(ObjectClone(data));
      });
      return;
    }
    //WHEN::Custom param, mixing component data(get##) and parentContext data(pack##)
    if (call instanceof Object) {
      const _call = ParamGet("_call", null, call);
      let _data = ObjectClone(ParamGet("_data", {}, call));
      const _packData = parentContext === null ? {} : ParamGet("_data", {}, parentContext);
      for (const key in _data) {
        let value = _data[key];
        if ((0,isString/* default */.A)(value)) if (value.startsWith('get##')) {
          _data[key] = ParamGet(value, null, data);
        } else if (value.startsWith('pack##')) {
          const getKey = 'get##' + value.substring('pack##'.length);
          _data[key] = ParamGet(getKey, null, _packData);
        }
      }
      if (typeof _call === "string" && _call.startsWith("pack##")) isPackCallUseData = true;
      return CallBack(_call, _data, event, parentContext, isSync, isFailMark, isPackCallUseData);
    }
  } catch (e) {
    console.debug("Common-Tools CallBack exception", e);
  }
}

;// ./Code/Common/Tools/_PubSub.js



const _PubSubQueue = {};

//TIPS::Subscribe PubSub
//>>id::The identity of the PubSub channel.Can listen to the same ID simultaneously
//>>executeFun::The call back function of receive information
//>>handler::The data object, it will be sent to 'executeFun' with PubSub message
//>>return::The token of the PubSub channel
//>>return::null
function PubSubListen(id, executeFun, handler) {
  try {
    //STEP::Subscribe message
    if (id === "") return null;
    const result = pubsub_default().subscribe(id, (topic, message) => {
      executeFun(message, handler);
    });
    //STEP::Resend fail message
    if (id in _PubSubQueue) {
      setTimeout(() => {
        for (const item of _PubSubQueue[id]) {
          pubsub_default().publish(id, item);
        }
      });
    }
    return result;
  } catch (e) {
    console.debug("Common-Tools PubSubListen exception", e);
  }
}

//TIPS::Unsubscribe PubSub
//>>token::The token of the PubSub channel(get from PubSubListen())
//>>return::null
function PubSubCancel(token) {
  try {
    if (token !== null) {
      pubsub_default().unsubscribe(token);
    }
  } catch (e) {
    console.debug("Common-Tools PubSubCancel exception", e);
  }
  return null;
}

//TIPS::Send PubSub message
//>>topic::The topic of the PubSub channel.It is usually the same as the id set by PubSubListen().You can also use "." to implement topic-based sending, such as when both "abc.one" and "abc.two" are being subscribed, sending "abc" will notify both channels
//>>message::The data will be sent
//>>isSync::Whether to synchronize sending
//>>isFailMark::If the sending fails, should it be recorded and then resent when there is a new listen
//>>return::true/false
function PubSubSend(topic, message) {
  let isSync = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : false;
  let isFailMark = arguments.length > 3 && arguments[3] !== undefined ? arguments[3] : true;
  let result = false;
  try {
    //STEP::Send message
    if (isSync) {
      result = pubsub_default().publishSync(topic, message);
      if (result === true || isFailMark === false) return result;
    }
    const copyData = (0,cloneDeep/* default */.A)(message);
    if (!isSync) result = pubsub_default().publish(topic, copyData);

    //WHEN::Send fail
    if (!result && isFailMark) {
      if (topic in _PubSubQueue) _PubSubQueue[topic].push(copyData);else _PubSubQueue[topic] = [copyData];
      result = true;
    }
  } catch (e) {
    console.debug("Common-Tools PubSubSend exception", e);
  }
  return result;
}

//TIPS::Check whether the id has been subscribed
//>>id::The id that needs to be checked
//>>return::true/false
function PubSubCheck(id) {
  try {
    return PubSub.hasSubscribers(id);
  } catch (e) {
    console.debug("Common-Tools PubSubCheck exception", e);
  }
  return false;
}

// EXTERNAL MODULE: ./node_modules/lodash-es/uniq.js + 9 modules
var uniq = __webpack_require__(4098);
// EXTERNAL MODULE: ./node_modules/lodash-es/merge.js + 18 modules
var merge = __webpack_require__(6338);
// EXTERNAL MODULE: ./node_modules/lodash-es/isPlainObject.js
var isPlainObject = __webpack_require__(4963);
;// ./Code/Common/Tools/_Merge.js




function MergeDefault_Deep(config) {
  let defaultConfig = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
  //WHEN::Allow anything
  if (defaultConfig === null) {
    if (typeof config === "undefined") return undefined;else return config;
  }

  //WHEN::Normal type(not {},[]) check
  if (typeof defaultConfig !== "object") if (typeof defaultConfig === typeof config) return config;else return defaultConfig;

  //WHEN::defaultConfig is empty([],{}), only constraint type
  if (Object.keys(defaultConfig).length === 0) if (typeof config === "undefined") return defaultConfig;else if (Array.isArray(defaultConfig) === Array.isArray(config)) return config;else return defaultConfig;

  //WHEN::defaultConfig is Object(not empty)
  const isArray = Array.isArray(defaultConfig);
  if (!isArray) {
    let result = {};
    //WHEN-IN::Different type
    if (typeof config === "object" && Array.isArray(config)) return defaultConfig;
    for (const key in defaultConfig) {
      if (config.hasOwnProperty(key)) {
        result[key] = MergeDefault_Deep(config[key], defaultConfig[key]);
      } else {
        if (Array.isArray(defaultConfig[key])) {
          result[key] = MergeDefault_Deep(config[key], defaultConfig[key]);
        } else result[key] = defaultConfig[key];
      }
    }
    return result;
  }

  //WHEN::defaultConfig is Array(not empty)
  else {
    //STEP-IN::Get range type
    let isRange = false;
    let isLockCount = false;
    if (defaultConfig.length > 1) {
      let typeList = [];
      for (let index = 0; index < defaultConfig.length; index++) typeList.push(Object.prototype.toString.call(defaultConfig[index]));
      typeList = (0,uniq/* default */.A)(typeList);
      if (typeList.length === defaultConfig.length) {
        isRange = true;
      } else if (typeList.length !== 1 && typeList.length !== defaultConfig.length) {
        isLockCount = true;
      }
    }

    //WHEN-IN::Range setting, not real list
    if (isRange) {
      if (config === undefined) return defaultConfig[0];
      const configType = Object.prototype.toString.call(config);
      for (let index = 0; index < defaultConfig.length; index++) {
        if (configType === Object.prototype.toString.call(defaultConfig[index])) {
          return MergeDefault_Deep(config, defaultConfig[index]);
        }
      }
      return defaultConfig[0];
    }

    //WHEN-IN::Lock count, one by one insert
    if (isLockCount) {
      const result = [];
      if (!Array.isArray(config)) return defaultConfig;
      for (let index = 0; index < defaultConfig.length; index++) {
        let item = index < config.length ? MergeDefault_Deep(config[index], defaultConfig[index]) : defaultConfig[index];
        result.push(item);
      }
      return result;
    }

    //WHEN-IN::List
    const result = [];
    if (!Array.isArray(config)) return defaultConfig;
    for (let index = 0; index < config.length; index++) {
      let item = MergeDefault_Deep(config[index], defaultConfig[0]);
      result.push(item);
    }
    return result;
  }
}

//TIPS::Merge object
//>>config::The config setting
//>>defaultConfig::Default setting
//                - If the types of 'config' and 'defaultConfig' are the same, the value of config will be returned, otherwise the value of defaultConfig will be adopted
//                - If defaultConfig is 'null', it means that the value type is not limited
//                - If defaultConfig is an array, and all element types are inconsistent, it is considered to be a value range. As long as config meets one of the types, it will be adopted
//                - If defaultConfig is an array, and there are elements of the same type, indicating an array of fixed sequences.Only the elements at the corresponding positions in the config that meet the type requirements will be accepted
//>>return::new object
function MergeDefault() {
  let config = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
  let defaultConfig = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
  try {
    //WHEN::isDeep is false, it means that there is no need to expand the object match
    return MergeDefault_Deep((0,cloneDeep/* default */.A)(config), (0,cloneDeep/* default */.A)(defaultConfig));
  } catch (e) {
    console.debug("Common-Tools MergeDefault exception", e);
    return defaultConfig;
  }
}

//TIPS::Merge object simply(Use merge of lodash-es)
//>>config::Value(Priority)
//>>defaultConfig::Supplementary value(Priority)
//>>return::new value
function Merge() {
  let config = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
  let defaultConfig = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
  try {
    if ((0,isPlainObject/* default */.A)(config) && (0,isPlainObject/* default */.A)(defaultConfig)) return (0,merge/* default */.A)({}, defaultConfig, config);else if (Array.isArray(config) && Array.isArray(defaultConfig)) return (0,merge/* default */.A)([], defaultConfig, config);
    return config;
  } catch (e) {
    console.debug("Common-Tools MergeDefault exception", e);
    return defaultConfig;
  }
}

// EXTERNAL MODULE: ./node_modules/@babel/runtime/helpers/esm/defineProperty.js + 3 modules
var defineProperty = __webpack_require__(4705);
// EXTERNAL MODULE: ./node_modules/lodash-es/isEqual.js + 7 modules
var isEqual = __webpack_require__(5010);
// EXTERNAL MODULE: ./Code/Common/Logger/Logger.js
var Logger = __webpack_require__(5507);
// EXTERNAL MODULE: ./node_modules/react/index.js
var react = __webpack_require__(6540);
// EXTERNAL MODULE: ./node_modules/lodash-es/isNumber.js
var isNumber = __webpack_require__(1879);
// EXTERNAL MODULE: ./Code/Common/Lang/Lang.js
var Lang = __webpack_require__(7803);
;// ./Code/Common/Tools/_Templ.js





const _PageTemplateMap = {};
let _PageCompMap = {};

//TIPS::Organize form templates and change template settings
function _DeepConfig(children, configDeep, baseConfig) {
  let template;
  const isList = Array.isArray(children);
  try {
    if (!Array.isArray(children) && !children["props"].hasOwnProperty("children")) {
      return children;
    }
    template = Array.isArray(children) ? children : children["props"]["children"];
  } catch (e) {
    return children;
  }
  template = react.Children.map(template, (child, index) => {
    let name = typeof child.type === "string" ? child.type : child.type.name;
    let newChild = child;

    //STEP::Deal path key
    const nestConfigDeep = {};
    let isNested = false;
    let thisConfig = false;
    for (let key in configDeep) {
      const config = configDeep[key];
      if (key === name || key === "$." + name) {
        thisConfig = config;
        continue;
      } else if (key === `${index}`) {
        thisConfig = config;
        continue;
      } else if (key.startsWith(`${name}>>`)) {
        key = key.substring(`${name}>>`.length);
      } else if (key.startsWith(`${index}>>`)) {
        key = key.substring(`${index}>>`.length);
      } else {
        continue;
      }
      isNested = true;
      nestConfigDeep[key] = config;
    }

    //STEP::Deep child find
    if (isNested && newChild["props"].hasOwnProperty("children")) newChild = _DeepConfig(newChild, nestConfigDeep, baseConfig);

    //STEP::Set this child config
    if (thisConfig !== false && !Array.isArray(newChild)) {
      if (newChild.hasOwnProperty("props") && newChild["props"].hasOwnProperty("config")) newChild = /*#__PURE__*/react.cloneElement(newChild, {
        config: (0,merge/* default */.A)({}, baseConfig, newChild["props"]["config"], thisConfig)
      });else newChild = /*#__PURE__*/react.cloneElement(newChild, {
        config: (0,merge/* default */.A)({}, baseConfig, thisConfig)
      });
    }
    return newChild;
  });

  //STEP::Restore Children
  if (isList) return template;else children = /*#__PURE__*/react.cloneElement(children, {
    children: template
  });
  return children;
}

//TIPS::Get inner child
function TemplGet_DeepTempl(indexArr, template) {
  let isFirst = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : false;
  //WHEN::End
  if (indexArr.length === 0) {
    return template;
  }

  //STEP::Get index
  let index = indexArr.shift();
  if (index === "") return template;
  index = isNaN(Number(index)) ? index : Number(index);

  //STEP::Get children
  try {
    if (!Array.isArray(template) && !template["props"].hasOwnProperty("children")) {
      return null;
    }
  } catch (e) {
    return null;
  }
  let children = template;
  if (!isFirst) children = Array.isArray(template) ? template : template["props"]["children"];
  children = react.Children.count(children) <= 1 && !Array.isArray(children) ? [children] : children;

  //WHEN::Index is number
  if ((0,isNumber/* default */.A)(index) && index >= 0 && index < children.length) {
    return TemplGet_DeepTempl(indexArr, children[index], false);
  }

  //WHEN::Index is not number
  for (const i in children) {
    const child = children[i];
    try {
      let name = typeof child.type === "string" ? child.type : child.type.name;
      if (index === name || index === "$." + name) {
        return TemplGet_DeepTempl(indexArr, child, false);
      }
    } catch (e) {}
  }
  return null;
}

//TIPS::For getting template
//>>setting::Get settings
//          - Array type([]), means getting list
//          - String type("layout##layout name", starting with 'layout##'), means getting from page layout(Add by TemplAdd())
//          **Trick2.2 and later versions have changed 'page##' to 'layout##'
//          - String type("child##", starting with 'child##'), means getting from children, you can specify children index, such as 'child##1'
//          - null, means the whole react children
//          - String type(""), means text, It will be translated automatically(use translate)
//          - Object type({}), detailed settings, the format is {"_templ":"","_config":{},"_configDeep":{}}, '_templ' equivalent to 'setting', "_config" equivalent to 'config', "_configDeep" equivalent to 'deepConfig'
//>>children::React component children
//>>baseConfig::Object type({}), it will be auto add to config/baseConfig or template 'config prop'
//>>config::Object type({}), it will be auto add to template 'config prop'
//>>deepConfig::Object type({}), the format is {"key":{},"key2":{}}, it will be auto add to the 'config prop' of in-layer template
//             - Key is customized, indicating the positioning of the in-layer template. Using '>>' positioning, you can use numbers or component names, for example, "div>>1>>2"
//             - Value is config object, it will be auto add to the 'config prop' of in-layer template
//>>translate::Get from useTranslate()
//>>return::template
//>>return::children(default)
const TemplGet = function (setting, children) {
  let baseConfig = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : {};
  let config = arguments.length > 3 && arguments[3] !== undefined ? arguments[3] : null;
  let deepConfig = arguments.length > 4 && arguments[4] !== undefined ? arguments[4] : null;
  let translate = arguments.length > 5 && arguments[5] !== undefined ? arguments[5] : null;
  try {
    //STEP::Get template
    let template = children;
    //WHEN::React component
    if (/*#__PURE__*/react.isValidElement(setting)) template = setting;
    //WHEN::Array call list
    else if (Array.isArray(setting)) {
      const element = [];
      for (const [index, item] of setting.entries()) {
        const piece = TemplGet(item, children, baseConfig, config, deepConfig, translate);
        element.push(piece);
      }
      template = element;
    }
    //WHEN::Object as detailed setting
    else if (typeof setting === "object" && setting !== null) {
      const _templ = ParamGet("_templ", null, setting);
      const _config = ParamGet("_config", {}, setting);
      const _configDeep = ParamGet("_configDeep", {}, setting);
      template = TemplGet(_templ, children, baseConfig, _config, _configDeep, translate);
    }
    //WHEN::Set UI component
    else if (typeof setting === "string" && setting.startsWith("$.")) {
      if (_PageCompMap.hasOwnProperty(setting)) template = _PageCompMap[setting];else template = setting;
    }
    //WHEN::Page layout as template
    else if (typeof setting === "string" && setting.startsWith("layout##")) {
      let index = setting.substring("layout##".length);
      let indexArr = index.split(">>");
      index = indexArr.shift();
      if (_PageTemplateMap.hasOwnProperty(index)) template = TemplGet_DeepTempl(indexArr, _PageTemplateMap[index](), false);else template = setting;
      if (template === null) template = setting;
    }
    //WHEN::Child as template
    else if (typeof setting === "string" && setting.startsWith("child##")) {
      const childrenMap = react.Children.count(children) <= 1 && !Array.isArray(children) ? [children] : children;
      let index = setting.substring("child##".length);
      let indexArr = index.split(">>");
      template = TemplGet_DeepTempl(indexArr, childrenMap, true);
      if (template === null) template = setting;
    }
    //WHEN::Text
    else if (typeof setting === "string") {
      if (config !== null) return Lang/* default */.Ay.TransTextConfig(setting, config, translate);else return Lang/* default */.Ay.TransText(setting, translate);
    }
    //WHEN::Illegal type
    else {
      template = children;
    }

    //STEP::Change deep config
    if (deepConfig !== null) {
      if (typeof deepConfig === 'object' && !Array.isArray(deepConfig) && Object.keys(deepConfig).length > 0) {
        template = _DeepConfig(template, deepConfig, baseConfig);
      }
    }

    //STEP::Change config
    try {
      if (config !== null) {
        if (typeof config === 'object' && !Array.isArray(config) && Object.keys(config).length > 0) {
          if (template["props"].hasOwnProperty("config")) {
            template = /*#__PURE__*/react.cloneElement(template, {
              config: (0,merge/* default */.A)({}, baseConfig, template["props"]["config"], config)
            });
          } else {
            template = /*#__PURE__*/react.cloneElement(template, {
              config: (0,merge/* default */.A)({}, baseConfig, config)
            });
          }
        }
      }
    } catch (e) {
      return template;
    }
    return template;
  } catch (e) {
    console.debug("Common-CompTools TemplGet exception", e);
  }
  return null;
};

//TIPS::For marking react function component(page layout)
//>>name::Component name
//>>template::react function component
const TemplAdd = function (name, template) {
  _PageTemplateMap[name] = template;
};

//TIPS::For marking ui component in config setting(_config)
//>>map::Component map
const TemplMark = function (map) {
  _PageCompMap = map;
};

;// ./Code/Common/Tools/_Comp.js







function ownKeys(e, r) { var t = Object.keys(e); if (Object.getOwnPropertySymbols) { var o = Object.getOwnPropertySymbols(e); r && (o = o.filter(function (r) { return Object.getOwnPropertyDescriptor(e, r).enumerable; })), t.push.apply(t, o); } return t; }
function _objectSpread(e) { for (var r = 1; r < arguments.length; r++) { var t = null != arguments[r] ? arguments[r] : {}; r % 2 ? ownKeys(Object(t), !0).forEach(function (r) { (0,defineProperty/* default */.A)(e, r, t[r]); }) : Object.getOwnPropertyDescriptors ? Object.defineProperties(e, Object.getOwnPropertyDescriptors(t)) : ownKeys(Object(t)).forEach(function (r) { Object.defineProperty(e, r, Object.getOwnPropertyDescriptor(t, r)); }); } return e; }








//TIPS::Pack component context
//>>'Pack component' will mark callback function and value in this variable
//>>The components under 'Pack component' can use Tools.CallBack() to call back 'Pack component'
const CompContext = /*#__PURE__*/react.createContext(null);

//TIPS::Update component state/data
//>>In order to extract the general code of the component
function CompConfigSet(stateConfig, setState, actionConfig, data) {
  try {
    setState(draft => {
      for (const key in stateConfig) draft[key] = stateConfig[key];
    });
    for (const key in actionConfig) data.current[key] = actionConfig[key];
  } catch (e) {
    console.debug("Common-Tools CompConfigSet exception", e);
  }
}

//TIPS::Component's normal 'Event' Action, such as onClick, onChange
//>>In order to extract the general code of the component
function CompActEvent(moduleParam, passParam, data, state, setState, element, event, parentContext, moduleName) {
  //STEP::Tips
  console.debug(Logger/* default */.A.Header(), `Component-${moduleName} Event, event`, event);

  //STEP::Call back(according the setting of data, such as '_onChange', '_onClick')
  let _call = ParamRead('_call', null, moduleParam, data.current);
  _call = _call === null && (0,isObject/* default */.A)(event) ? ParamGet(`_${event._reactName}`, null, data.current) : _call;
  let _data = ParamGet("_data", null, moduleParam);

  //STEP::Stop propagation
  try {
    if ((0,isObject/* default */.A)(event) && (0,isObject/* default */.A)(_call) && !Array.isArray(_call)) {
      let _isStop = false;
      if (_call.hasOwnProperty("_isStop")) {
        _isStop = _call["_isStop"] === true;
      }
      if (_isStop === true) {
        console.debug(Logger/* default */.A.Header(), `Component-${moduleName} Event, stop propagation`);
        event.stopPropagation();
      }
    }
  } catch (e) {}

  //STEP::Call Back
  setState(draft => {
    _data = _data === null ? ObjectClone(_objectSpread(_objectSpread({}, data.current), draft)) : _data;
    console.debug(Logger/* default */.A.Header(), `Component-${moduleName} Event, _call`, _call);
    console.debug(Logger/* default */.A.Header(), `Component-${moduleName} Event, _data`, _data);
    CallBack(_call, _data, event, parentContext, false, true);
  });
}

//TIPS::Component's normal 'Get' Action, get data/state from component
//>>In order to extract the general code of the component
function CompActGet(moduleParam, passParam, data, state, setState, element, event, parentContext, moduleName) {
  //STEP::Get setting
  const _resultKey = ParamRead("_resultKey", "", moduleParam, passParam);
  console.debug(Logger/* default */.A.Header(), `Component-${moduleName} Get, _resultKey`, _resultKey);

  //STEP::Get data/state
  const result = _objectSpread(_objectSpread({}, data.current), state);

  //STEP::Deal result
  let targetParam = passParam === null ? moduleParam : passParam;
  if (_resultKey === "") {
    ObjectClean(targetParam);
    ObjectCopy(targetParam, result);
  } else targetParam[_resultKey] = result;
}
function CompActSet_Param(key, oldValue, defalutValue, moduleParam, passParam, isNec, isPush, pushIndex) {
  let value = ParamRead(key, null, moduleParam, passParam);
  if (!isNec && (0,isPlainObject/* default */.A)(value) && (0,isPlainObject/* default */.A)(oldValue)) value = (0,merge/* default */.A)({}, oldValue, value);else if (!isNec && Array.isArray(value) && Array.isArray(oldValue)) value = (0,merge/* default */.A)([], oldValue, value);
  if (isPush && Array.isArray(oldValue)) {
    if (pushIndex < 0 || pushIndex >= oldValue.length) {
      if (Array.isArray(value)) value = [...oldValue, ...value];else value = [...oldValue, value];
    } else {
      oldValue[pushIndex] = value;
      value = oldValue;
    }
  }
  return MergeDefault(value, defalutValue);
}

//TIPS::Component's normal 'Set' Action, set component's data/state
//>>In order to extract the general code of the component
function CompActSet(moduleParam, passParam, data, state, setState, element, event, parentContext, moduleName, configActionDefault, configUIDefault, templateMark) {
  //TIPS::Set
  const _refresh = ParamRead("_refresh", false, moduleParam, passParam);
  console.debug(Logger/* default */.A.Header(), `Component-${moduleName} Set, _refresh`, _refresh);

  //WHEN::Need to refresh template
  if (_refresh) templateMark.current = {};

  //STEP::Update setting
  for (let key in moduleParam) {
    //STEP::Get special function settings
    let isNec = false;
    let isPush = false;
    let pushIndex = -1;
    const keyOrigin = key;
    if (key.startsWith("nec##")) {
      isNec = true;
      key = key.substring("nec##".length);
    } else if (key.startsWith("push##")) {
      isPush = true;
      key = key.substring("push##".length);
      const regex = /^(\d+)##/;
      const match = key.match(regex);
      if (match) {
        pushIndex = match[1];
        key = key.replace(regex, '');
      }
    }
    if (key in data.current) {
      data.current[key] = CompActSet_Param(keyOrigin, data.current[key], configActionDefault[key], moduleParam, passParam, isNec, isPush, pushIndex);
    }
    if (key in state) {
      setState(draft => {
        draft[key] = CompActSet_Param(keyOrigin, (0,cloneDeep/* default */.A)(state[key]), configUIDefault[key], moduleParam, passParam, isNec, isPush, pushIndex);
      });
    }
  }
}

//TIPS::For component action call, such as onClick, onChange
//>>In order to extract the general code of the component
function CompActCall(actionCall, handler) {
  let param = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : {};
  let isCall = arguments.length > 3 && arguments[3] !== undefined ? arguments[3] : true;
  if (isCall === true) {
    return event => {
      Logger/* default */.A.SetId();
      actionCall(param, handler, event);
    };
  }
  return () => {};
}

//TIPS::For pack component mark parentContext value
//>>In order to extract the general code of the component
function CompChildCall(actionCall, handler) {
  let param = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : {};
  let isCall = arguments.length > 3 && arguments[3] !== undefined ? arguments[3] : true;
  const result = {
    "_data": param,
    "_call": () => {}
  };
  if (isCall === true) {
    result["_call"] = function () {
      let data = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
      let event = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : null;
      actionCall(data, handler, event);
    };
  }
  return result;
}
function CompTemplGet_ArrayGet(template, setting, children, baseConfig, config, deepConfig, translate) {
  const element = [];
  for (let [index, item] of template.entries()) {
    if (Array.isArray(item)) {
      item = CompTemplGet_ArrayGet(item, setting[index], children, baseConfig, config, deepConfig, translate);
    } else if ((0,isString/* default */.A)(item)) {
      item = TemplGet(setting[index], children, baseConfig, config, deepConfig, translate);
    }
    element.push(/*#__PURE__*/react.createElement(react.Fragment, {
      key: index
    }, item));
  }
  return /*#__PURE__*/react.createElement(react.Fragment, null, element);
}
function CompTemplGet_Array(template, mark) {
  const element = [];
  for (let [index, item] of template.entries()) {
    if (Array.isArray(item)) {
      item = CompTemplGet_Array(item);
    } else if ((0,isString/* default */.A)(item)) {
      mark["hasString"] = true;
    }
    element.push(/*#__PURE__*/react.createElement(react.Fragment, {
      key: index
    }, item));
  }
  return /*#__PURE__*/react.createElement(react.Fragment, null, element);
}

//TIPS::Get template, translate text/img
//>>state::Component state object
//        -If the key starts with '_templ', means getting template
//         --If the value is string type("layout##layout name", starting with 'layout##'), means getting from page layout(Add by TemplAdd())
//         **Trick2.2 and later versions have changed 'page##' to 'layout##'
//         --If the value is string type("child##", starting with 'child##'), means getting from children, you can specify children index, such as 'child##1'
//         --If the value is null, means the whole react children
//         --If the value is string type(""), means text, It will be translated automatically(use translate)
//         --If the value is object type({}), detailed settings, the format is {"_templ":"","_config":{},"_configDeep":{}}
//        -If the key starts with '_config', means template config setting, Reference the description of Tools.TemplGet()
//        -If the key starts with '_configDeep', means template deep config setting, Reference the description of Tools.TemplGet()
//         --'_templ','_config','_configDeep' have a correspondence, requiring the same suffix of key, for example, '_templXXX','_configXXX','_configDeepXXX'
//         --If there is a '_config' or '_configDeep', the whole object will be passed as 'baseConfig' when calling Tools.TemplGet()
//        -If the key starts with '_text', means translate text, values can be string type or object type
//         --If value is object type, means translate with parameters, the format is '{_text:"xxx", "key":"value"}', '_text' is text key
//        -If the key starts with '_img'(value must be string type), means translate img src
//>>templateMark::The objects that recorded the generated templates
//>>children::React component children
//>>translate::Get from useTranslate()
//>>return::new component state, replacing template/text/img
function CompTemplGet(state, templateMark, children) {
  let translate = arguments.length > 3 && arguments[3] !== undefined ? arguments[3] : null;
  try {
    //WHEN::state is not object
    if (typeof state !== "object") return state;
    if (state === null) {
      return null;
    }
    if (typeof state === "undefined") return undefined;

    //STEP::Deal result
    const result = Array.isArray(state) ? [] : {};
    for (const key in state) {
      const value = state[key];

      //WHEN-IN::Get template
      if (key.startsWith("_templ")) {
        const setting = value;
        const addKey = key.substring("_templ".length);
        const config = `_config${addKey}` in state ? state[`_config${addKey}`] : {};
        const configDeep = `_configDeep${addKey}` in state ? state[`_configDeep${addKey}`] : {};
        if (key in templateMark) {
          const template = templateMark[key];
          if ((/*#__PURE__*/react.isValidElement(setting) === true && /*#__PURE__*/react.isValidElement(template["_templ"]) === true || (0,isEqual/* default */.A)(setting, template["_templ"])) && (0,isEqual/* default */.A)(config, template["_config"]) && (0,isEqual/* default */.A)(configDeep, template["_configDeep"])) {
            if (template["hasString"] === true) result[key] = CompTemplGet_ArrayGet(template["template"], setting, children, {}, config, configDeep, translate);else result[key] = template["template"];
            continue;
          }
        }
        let template = TemplGet(setting, children, {}, config, configDeep, translate);
        templateMark[key] = {};
        if (Array.isArray(template)) {
          templateMark[key]["hasString"] = false;
          templateMark[key]["_templ"] = setting;
          templateMark[key]["_config"] = config;
          templateMark[key]["_configDeep"] = configDeep;
          templateMark[key]["template"] = template;
          templateMark[key]["lang"] = Lang/* default */.Ay.GetLanguage();
          template = CompTemplGet_Array(template, templateMark[key]);
          if (templateMark[key]["hasString"] === false) templateMark[key]["template"] = template;
        } else if (!(0,isString/* default */.A)(template)) {
          templateMark[key]["_templ"] = setting;
          templateMark[key]["_config"] = config;
          templateMark[key]["_configDeep"] = configDeep;
          templateMark[key]["template"] = template;
          templateMark[key]["lang"] = Lang/* default */.Ay.GetLanguage();
          templateMark[key]["hasString"] = false;
        }
        result[key] = template;
      }

      //WHEN-IN::Translate text
      else if (key.startsWith("_text")) result[key] = Lang/* default */.Ay.TransText(value, translate);

      //WHEN-IN::Translate src
      else if (key.startsWith("_src")) result[key] = Lang/* default */.Ay.TransSrc(value, translate);

      //WHEN-IN::Deep find
      else if (!key.startsWith("_config") && typeof value === "object") {
        if (!(key in templateMark)) templateMark[key] = {};
        if (typeof value !== typeof templateMark[key] || Array.isArray(value) !== Array.isArray(templateMark[key])) templateMark[key] = Array.isArray(value) ? [] : {};
        result[key] = CompTemplGet(value, templateMark[key], children, translate);
      }

      //WHEN-IN::Other setting
      else result[key] = state[key];
    }
    return result;
  } catch (e) {
    console.debug("Common-Tools CompTemplGet exception", e);
    return state;
  }
}

;// ./Code/Common/Tools/Tools.js










/***/ }),

/***/ 7589:
/***/ (function(__unused_webpack_module, __webpack_exports__, __webpack_require__) {

/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   D: function() { return /* binding */ useTheme; },
/* harmony export */   S: function() { return /* binding */ Theme; }
/* harmony export */ });
/* harmony import */ var _Code_Common_Config_Config__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(519);
/* harmony import */ var _Code_Common_Tools_Tools__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(6543);
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(6540);



const Config = _Code_Common_Tools_Tools__WEBPACK_IMPORTED_MODULE_1__/* .MergeDefault */ .di(_Code_Common_Config_Config__WEBPACK_IMPORTED_MODULE_0__/* ["default"] */ .A.common, {
  "Theme.enable": true,
  "Theme.range": ["", "dark"]
});
const Theme = {
  Enable: false,
  Theme: document.documentElement.getAttribute('trick-theme'),
  Init: function () {
    if (!Config["Theme.enable"]) {
      return;
    }
    let theme = localStorage.getItem('Trick_Common_Theme');
    if (theme === null) {
      theme = document.documentElement.getAttribute('trick-theme');
      theme = theme === null ? "" : theme;
    }
    localStorage.setItem('Trick_Common_Theme', theme);
    document.documentElement.setAttribute('trick-theme', theme);
    Theme.Theme = theme;
    Theme.Enable = true;
  },
  Change: function (theme) {
    if (!Theme.Enable) return;
    if (!Config["Theme.range"].includes(theme)) return;
    localStorage.setItem('Trick_Common_Theme', theme);
    document.documentElement.setAttribute('trick-theme', theme);
    Theme.Theme = theme;
    window.dispatchEvent(new Event('trick-theme'));
  },
  GetTheme: function () {
    if (!Theme.Enable) return "";
    return document.documentElement.getAttribute('trick-theme');
  }
};

//TIPS::For refreshing component
function useTheme() {
  const [theme, setTheme] = (0,react__WEBPACK_IMPORTED_MODULE_2__.useState)(Theme.Theme);
  (0,react__WEBPACK_IMPORTED_MODULE_2__.useEffect)(() => {
    const handleThemeChange = () => {
      setTheme(document.documentElement.getAttribute('trick-theme'));
    };
    if (Theme.Enable) window.addEventListener('trick-theme', handleThemeChange);
    return () => {
      if (Theme.Enable) window.removeEventListener('trick-theme', handleThemeChange);
    };
  }, []);
  return theme;
}

/***/ }),

/***/ 7803:
/***/ (function(__unused_webpack_module, __webpack_exports__, __webpack_require__) {

/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   rs: function() { return /* binding */ useLangDir; }
/* harmony export */ });
/* unused harmony export Lang */
/* harmony import */ var lodash_es_isObject__WEBPACK_IMPORTED_MODULE_8__ = __webpack_require__(3149);
/* harmony import */ var i18next__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(2635);
/* harmony import */ var react_i18next__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(2389);
/* harmony import */ var i18next_http_backend__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(1347);
/* harmony import */ var i18next_browser_languagedetector__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(4997);
/* harmony import */ var _Code_Common_Config_Config__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(519);
/* harmony import */ var _Code_Common_Theme_Theme__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(7589);
/* harmony import */ var _Code_Common_Tools_Tools__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(6543);
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(6540);









const Config = _Code_Common_Tools_Tools__WEBPACK_IMPORTED_MODULE_6__/* .MergeDefault */ .di(_Code_Common_Config_Config__WEBPACK_IMPORTED_MODULE_4__/* ["default"] */ .A.common, {
  "Lang.enable": true,
  "Lang.range": ["def", "en"],
  "Lang.path": "/web/base/lang",
  "Lang.srcPrefix": "/web/base/assets",
  "Lang.srcPrefixRequire": "//"
});
const Lang = {
  Enable: false,
  Dir: "",
  Init: function (page) {
    if (!Config["Lang.enable"]) {
      return;
    }

    //STEP::i18next init
    i18next__WEBPACK_IMPORTED_MODULE_0__/* ["default"].use */ .Ay.use(i18next_http_backend__WEBPACK_IMPORTED_MODULE_2__/* ["default"] */ .A).use(i18next_browser_languagedetector__WEBPACK_IMPORTED_MODULE_3__/* ["default"] */ .A).use(react_i18next__WEBPACK_IMPORTED_MODULE_1__/* .initReactI18next */ .r9).init({
      debug: false,
      // ns: Config["Lang.nameSpace"],
      // defaultNS: Config["Lang.nameSpace"][0],
      nsSeparator: false,
      keySeparator: false,
      supportedLngs: Config["Lang.range"],
      fallbackLng: Config["Lang.range"][0],
      interpolation: {
        escapeValue: false
      },
      detection: {
        order: ["localStorage", "navigator"],
        caches: ['localStorage']
      },
      backend: {
        loadPath: `${Config["Lang.path"]}/${page}-{{lng}}.json`
      }
    });
    i18next__WEBPACK_IMPORTED_MODULE_0__/* ["default"].t */ .Ay.t("");
    Lang.Enable = true;

    //STEP::Listen language change(SPA page)
    window.addEventListener('trick-lang', () => {
      const lang = document.documentElement.getAttribute('lang');
      if (lang !== i18next__WEBPACK_IMPORTED_MODULE_0__/* ["default"] */ .Ay.language) Lang.Change(lang);
    });

    //STEP::Listen language change
    document.documentElement.setAttribute('dir', Lang.Dir);
    document.body.querySelector("#id_body").setAttribute('dir', Lang.Dir);
    i18next__WEBPACK_IMPORTED_MODULE_0__/* ["default"] */ .Ay.on('languageChanged', lang => {
      //STEP-IN::Notify dir change
      let dir = "";
      if (i18next__WEBPACK_IMPORTED_MODULE_0__/* ["default"].dir */ .Ay.dir(lang) === "rtl") dir = "rtl";
      if (dir !== Lang.Dir) {
        Lang.Dir = dir;
        document.documentElement.setAttribute('dir', Lang.Dir);
        document.body.querySelector("#id_body").setAttribute('dir', Lang.Dir);
        document.body.dispatchEvent(new Event('trick-lang'));
      }

      //STEP-IN::Notify lang change
      document.documentElement.setAttribute('lang', lang);
      window.dispatchEvent(new Event('trick-lang'));
    });
  },
  InitSimple: function (lang, resources) {
    //STEP::i18next init
    i18next__WEBPACK_IMPORTED_MODULE_0__/* ["default"].use */ .Ay.use(react_i18next__WEBPACK_IMPORTED_MODULE_1__/* .initReactI18next */ .r9).init({
      lng: lang,
      nsSeparator: false,
      keySeparator: false,
      interpolation: {
        escapeValue: false
      },
      resources: resources
      // {
      //     def: {
      //         translation: {
      //             "key": "hello world"
      //         }
      //     }
      // }
    });
    Lang.Enable = true;
    if (i18next__WEBPACK_IMPORTED_MODULE_0__/* ["default"].dir */ .Ay.dir(lang) === "rtl") {
      document.documentElement.setAttribute('dir', "rtl");
      Lang.Dir = "rtl";
    } else {
      document.documentElement.setAttribute('dir', "");
      Lang.Dir = "";
    }
    document.documentElement.setAttribute('lang', lang);

    //STEP::Listen language change
    document.documentElement.setAttribute('dir', Lang.Dir);
    i18next__WEBPACK_IMPORTED_MODULE_0__/* ["default"] */ .Ay.on('languageChanged', lang => {
      //STEP-IN::Notify dir change
      let dir = "";
      if (i18next__WEBPACK_IMPORTED_MODULE_0__/* ["default"].dir */ .Ay.dir(lang) === "rtl") dir = "rtl";
      if (dir !== Lang.Dir) {
        Lang.Dir = dir;
        document.documentElement.setAttribute('dir', Lang.Dir);
        document.body.dispatchEvent(new Event('trick-lang'));
      }

      //STEP-IN::Notify lang change
      document.documentElement.setAttribute('lang', lang);
      window.dispatchEvent(new Event('trick-lang'));
    });
  },
  Change: function (language) {
    if (!Lang.Enable) return;
    if (!Config["Lang.range"].includes(language)) return;
    i18next__WEBPACK_IMPORTED_MODULE_0__/* ["default"].changeLanguage */ .Ay.changeLanguage(language);
  },
  GetLanguage: function () {
    if (!Lang.Enable) return "";
    return i18next__WEBPACK_IMPORTED_MODULE_0__/* ["default"] */ .Ay.language;
  },
  TransText: function (text) {
    let translate = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : null;
    if (typeof text === "string") {
      if (translate === null) {
        return Lang.Enable ? i18next__WEBPACK_IMPORTED_MODULE_0__/* ["default"].t */ .Ay.t(text) : text;
      } else {
        return Lang.Enable ? translate(text) : text;
      }
    } else if ((0,lodash_es_isObject__WEBPACK_IMPORTED_MODULE_8__/* ["default"] */ .A)(text)) {
      if (text.hasOwnProperty("_text") && typeof text["_text"] === "string") {
        if (translate === null) {
          return Lang.Enable ? i18next__WEBPACK_IMPORTED_MODULE_0__/* ["default"].t */ .Ay.t(text["_text"], text) : text["_text"];
        } else {
          return Lang.Enable ? translate(text["_text"], text) : text["_text"];
        }
      }
      return text;
    } else return text;
  },
  TransTextConfig: function (text, config) {
    let translate = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : null;
    if (translate === null) {
      return Lang.Enable ? i18next__WEBPACK_IMPORTED_MODULE_0__/* ["default"].t */ .Ay.t(text, config) : text;
    } else {
      return Lang.Enable ? translate(text, config) : text;
    }
  },
  TransSrc: function (text) {
    if (typeof text === "string") {
      text = text.replaceAll('{lng}', Lang.Enable ? i18next__WEBPACK_IMPORTED_MODULE_0__/* ["default"] */ .Ay.language : "");
      text = text.replaceAll('{theme}', _Code_Common_Theme_Theme__WEBPACK_IMPORTED_MODULE_5__/* .Theme */ .S.GetTheme());
      if (text.startsWith(Config["Lang.srcPrefixRequire"])) return `${Config["Lang.srcPrefix"]}${text}`.replace(/\/+/g, '/');
      return text;
    }
    return text;
  }
};
/* harmony default export */ __webpack_exports__.Ay = (Lang);

//TIPS::For refreshing component
function useLangDir() {
  const [dir, setDir] = (0,react__WEBPACK_IMPORTED_MODULE_7__.useState)(Lang.Dir);
  (0,react__WEBPACK_IMPORTED_MODULE_7__.useEffect)(() => {
    const handleLangChange = () => {
      setDir(Lang.Dir);
    };
    if (Lang.Enable) document.body.addEventListener('trick-lang', handleLangChange);
    return () => {
      if (Lang.Enable) document.body.removeEventListener('trick-lang', handleLangChange);
    };
  }, []);
  return dir;
}

/***/ })

}]);